export const HubPoolAbi = [
  { inputs: [], name: "AccessControlBadConfirmation", type: "error" },
  {
    inputs: [{ internalType: "uint48", name: "schedule", type: "uint48" }],
    name: "AccessControlEnforcedDefaultAdminDelay",
    type: "error",
  },
  { inputs: [], name: "AccessControlEnforcedDefaultAdminRules", type: "error" },
  {
    inputs: [{ internalType: "address", name: "defaultAdmin", type: "address" }],
    name: "AccessControlInvalidDefaultAdmin",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "bytes32", name: "neededRole", type: "bytes32" },
    ],
    name: "AccessControlUnauthorizedAccount",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "allowance", type: "uint256" },
      { internalType: "uint256", name: "needed", type: "uint256" },
    ],
    name: "ERC20InsufficientAllowance",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "sender", type: "address" },
      { internalType: "uint256", name: "balance", type: "uint256" },
      { internalType: "uint256", name: "needed", type: "uint256" },
    ],
    name: "ERC20InsufficientBalance",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "approver", type: "address" }],
    name: "ERC20InvalidApprover",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "receiver", type: "address" }],
    name: "ERC20InvalidReceiver",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "sender", type: "address" }],
    name: "ERC20InvalidSender",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "spender", type: "address" }],
    name: "ERC20InvalidSpender",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint256", name: "maxLoan", type: "uint256" }],
    name: "ERC3156ExceededMaxLoan",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "receiver", type: "address" }],
    name: "ERC3156InvalidReceiver",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "ERC3156UnsupportedToken",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint16", name: "chainId", type: "uint16" }],
    name: "ExistingChainSpoke",
    type: "error",
  },
  { inputs: [], name: "FlashLoanFeeTooHigh", type: "error" },
  { inputs: [], name: "MathOverflowedMulDiv", type: "error" },
  { inputs: [], name: "MaxStableInterestRateTooHigh", type: "error" },
  { inputs: [], name: "MaxVariableInterestRateTooHigh", type: "error" },
  {
    inputs: [{ internalType: "uint16", name: "chainId", type: "uint16" }],
    name: "NoChainSpoke",
    type: "error",
  },
  { inputs: [], name: "OptimalStableToTotalDebtRatioTooHigh", type: "error" },
  { inputs: [], name: "OptimalUtilisationRatioTooHigh", type: "error" },
  { inputs: [], name: "OptimalUtilisationRatioTooLow", type: "error" },
  { inputs: [], name: "RatioExceedsOne", type: "error" },
  { inputs: [], name: "RebalanceUpDepositInterestRateTooHigh", type: "error" },
  { inputs: [], name: "RebalanceUpUtilisationRatioTooHigh", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [], name: "RetentionRateTooHigh", type: "error" },
  {
    inputs: [
      { internalType: "uint8", name: "bits", type: "uint8" },
      { internalType: "uint256", name: "value", type: "uint256" },
    ],
    name: "SafeCastOverflowedUintDowncast",
    type: "error",
  },
  { inputs: [], name: "StableBorrowPercentageTooHigh", type: "error" },
  {
    inputs: [
      { internalType: "uint16", name: "chainId", type: "uint16" },
      { internalType: "bytes32", name: "expected", type: "bytes32" },
      { internalType: "bytes32", name: "actual", type: "bytes32" },
    ],
    name: "UnmatchedChainSpoke",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "ClearTokenFees",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "DefaultAdminDelayChangeCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint48",
        name: "newDelay",
        type: "uint48",
      },
      {
        indexed: false,
        internalType: "uint48",
        name: "effectSchedule",
        type: "uint48",
      },
    ],
    name: "DefaultAdminDelayChangeScheduled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "DefaultAdminTransferCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newAdmin",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint48",
        name: "acceptSchedule",
        type: "uint48",
      },
    ],
    name: "DefaultAdminTransferScheduled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "variableBorrowInterestIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "depositInterestIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lastUpdateTimestamp",
        type: "uint256",
      },
    ],
    name: "InterestIndexesUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "variableBorrowInterestRate",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "stableBorrowInterestRate",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "depositInterestRate",
        type: "uint256",
      },
    ],
    name: "InterestRatesUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "bytes32",
        name: "previousAdminRole",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "newAdminRole",
        type: "bytes32",
      },
    ],
    name: "RoleAdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "HUB_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LOAN_MANAGER_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ORACLE_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PARAM_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "acceptDefaultAdminTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "spender", type: "address" },
    ],
    name: "allowance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newAdmin", type: "address" }],
    name: "beginDefaultAdminTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "sender", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "burnFToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "cancelDefaultAdminTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint48", name: "newDelay", type: "uint48" }],
    name: "changeDefaultAdminDelay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "clearTokenFees",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultAdmin",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultAdminDelay",
    outputs: [{ internalType: "uint48", name: "", type: "uint48" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultAdminDelayIncreaseWait",
    outputs: [{ internalType: "uint48", name: "", type: "uint48" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
    ],
    name: "flashFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IERC3156FlashBorrower",
        name: "receiver",
        type: "address",
      },
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "flashLoan",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCapsData",
    outputs: [
      {
        components: [
          { internalType: "uint64", name: "deposit", type: "uint64" },
          { internalType: "uint64", name: "borrow", type: "uint64" },
          {
            internalType: "uint64",
            name: "stableBorrowPercentage",
            type: "uint64",
          },
        ],
        internalType: "struct HubPoolState.CapsData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint16", name: "chainId", type: "uint16" }],
    name: "getChainSpoke",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getConfigData",
    outputs: [
      {
        components: [
          { internalType: "bool", name: "deprecated", type: "bool" },
          { internalType: "bool", name: "stableBorrowSupported", type: "bool" },
          { internalType: "bool", name: "canMintFToken", type: "bool" },
          { internalType: "bool", name: "flashLoanSupported", type: "bool" },
        ],
        internalType: "struct HubPoolState.ConfigData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getDepositData",
    outputs: [
      {
        components: [
          {
            internalType: "uint16",
            name: "optimalUtilisationRatio",
            type: "uint16",
          },
          { internalType: "uint256", name: "totalAmount", type: "uint256" },
          { internalType: "uint256", name: "interestRate", type: "uint256" },
          { internalType: "uint256", name: "interestIndex", type: "uint256" },
        ],
        internalType: "struct HubPoolState.DepositData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getFeeData",
    outputs: [
      {
        components: [
          { internalType: "uint32", name: "flashLoanFee", type: "uint32" },
          { internalType: "uint32", name: "retentionRate", type: "uint32" },
          {
            internalType: "address",
            name: "fTokenFeeRecipient",
            type: "address",
          },
          { internalType: "address", name: "tokenFeeClaimer", type: "address" },
          {
            internalType: "uint256",
            name: "totalRetainedAmount",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "tokenFeeRecipient",
            type: "bytes32",
          },
        ],
        internalType: "struct HubPoolState.FeeData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLastUpdateTimestamp",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOracleManager",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPoolId",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IBridgeRouter",
        name: "bridgeRouter",
        type: "address",
      },
      { internalType: "uint16", name: "adapterId", type: "uint16" },
      { internalType: "uint256", name: "gasLimit", type: "uint256" },
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
      { internalType: "uint16", name: "chainId", type: "uint16" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "bytes32", name: "recipient", type: "bytes32" },
    ],
    name: "getSendTokenMessage",
    outputs: [
      {
        components: [
          {
            components: [
              { internalType: "uint16", name: "adapterId", type: "uint16" },
              {
                internalType: "uint16",
                name: "returnAdapterId",
                type: "uint16",
              },
              {
                internalType: "uint256",
                name: "receiverValue",
                type: "uint256",
              },
              { internalType: "uint256", name: "gasLimit", type: "uint256" },
              {
                internalType: "uint256",
                name: "returnGasLimit",
                type: "uint256",
              },
            ],
            internalType: "struct Messages.MessageParams",
            name: "params",
            type: "tuple",
          },
          { internalType: "bytes32", name: "sender", type: "bytes32" },
          {
            internalType: "uint16",
            name: "destinationChainId",
            type: "uint16",
          },
          { internalType: "bytes32", name: "handler", type: "bytes32" },
          { internalType: "bytes", name: "payload", type: "bytes" },
          { internalType: "uint64", name: "finalityLevel", type: "uint64" },
          { internalType: "bytes", name: "extraArgs", type: "bytes" },
        ],
        internalType: "struct Messages.MessageToSend",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getStableBorrowData",
    outputs: [
      {
        components: [
          { internalType: "uint32", name: "sr0", type: "uint32" },
          { internalType: "uint32", name: "sr1", type: "uint32" },
          { internalType: "uint32", name: "sr2", type: "uint32" },
          { internalType: "uint32", name: "sr3", type: "uint32" },
          {
            internalType: "uint16",
            name: "optimalStableToTotalDebtRatio",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "rebalanceUpUtilisationRatio",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "rebalanceUpDepositInterestRate",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "rebalanceDownDelta",
            type: "uint16",
          },
          { internalType: "uint256", name: "totalAmount", type: "uint256" },
          { internalType: "uint256", name: "interestRate", type: "uint256" },
          {
            internalType: "uint256",
            name: "averageInterestRate",
            type: "uint256",
          },
        ],
        internalType: "struct HubPoolState.StableBorrowData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTokenFeeClaimer",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTokenFeeRecipient",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getUpdatedDepositInterestIndex",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getUpdatedVariableBorrowInterestIndex",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getVariableBorrowData",
    outputs: [
      {
        components: [
          { internalType: "uint32", name: "vr0", type: "uint32" },
          { internalType: "uint32", name: "vr1", type: "uint32" },
          { internalType: "uint32", name: "vr2", type: "uint32" },
          { internalType: "uint256", name: "totalAmount", type: "uint256" },
          { internalType: "uint256", name: "interestRate", type: "uint256" },
          { internalType: "uint256", name: "interestIndex", type: "uint256" },
        ],
        internalType: "struct HubPoolState.VariableBorrowData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "maxFlashLoan",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "mintFToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "mintFTokenForFeeRecipient",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingDefaultAdmin",
    outputs: [
      { internalType: "address", name: "newAdmin", type: "address" },
      { internalType: "uint48", name: "schedule", type: "uint48" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingDefaultAdminDelay",
    outputs: [
      { internalType: "uint48", name: "newDelay", type: "uint48" },
      { internalType: "uint48", name: "schedule", type: "uint48" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "poolId",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "maxStableRate", type: "uint256" },
    ],
    name: "preparePoolForBorrow",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "variableInterestIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "stableInterestRate",
            type: "uint256",
          },
        ],
        internalType: "struct DataTypes.BorrowPoolParams",
        name: "borrowPoolParams",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "preparePoolForRebalanceDown",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "variableInterestIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "stableInterestRate",
            type: "uint256",
          },
          { internalType: "uint256", name: "threshold", type: "uint256" },
        ],
        internalType: "struct DataTypes.RebalanceDownPoolParams",
        name: "rebalanceDownPoolParams",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "preparePoolForRebalanceUp",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "variableInterestIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "stableInterestRate",
            type: "uint256",
          },
        ],
        internalType: "struct DataTypes.BorrowPoolParams",
        name: "borrowPoolParams",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "preparePoolForRepay",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "variableInterestIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "stableInterestRate",
            type: "uint256",
          },
        ],
        internalType: "struct DataTypes.BorrowPoolParams",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "maxStableRate", type: "uint256" },
    ],
    name: "preparePoolForSwitchBorrowType",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "variableInterestIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "stableInterestRate",
            type: "uint256",
          },
        ],
        internalType: "struct DataTypes.BorrowPoolParams",
        name: "borrowPoolParams",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "bool", name: "isFAmount", type: "bool" },
    ],
    name: "preparePoolForWithdraw",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "underlingAmount", type: "uint256" },
          { internalType: "uint256", name: "fAmount", type: "uint256" },
        ],
        internalType: "struct DataTypes.WithdrawPoolParams",
        name: "withdrawPoolParams",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "preparePoolForWithdrawFToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rollbackDefaultAdminDelay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "uint64", name: "deposit", type: "uint64" },
          { internalType: "uint64", name: "borrow", type: "uint64" },
          {
            internalType: "uint64",
            name: "stableBorrowPercentage",
            type: "uint64",
          },
        ],
        internalType: "struct HubPoolState.CapsData",
        name: "capsData",
        type: "tuple",
      },
    ],
    name: "updateCapsData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "bool", name: "deprecated", type: "bool" },
          { internalType: "bool", name: "stableBorrowSupported", type: "bool" },
          { internalType: "bool", name: "canMintFToken", type: "bool" },
          { internalType: "bool", name: "flashLoanSupported", type: "bool" },
        ],
        internalType: "struct HubPoolState.ConfigData",
        name: "configData",
        type: "tuple",
      },
    ],
    name: "updateConfigData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "optimalUtilisationRatio",
        type: "uint16",
      },
    ],
    name: "updateDepositData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "flashLoanFee", type: "uint32" },
      { internalType: "uint32", name: "retentionRate", type: "uint32" },
      { internalType: "address", name: "fTokenFeeRecipient", type: "address" },
      { internalType: "address", name: "tokenFeeClaimer", type: "address" },
      { internalType: "bytes32", name: "tokenFeeRecipient", type: "bytes32" },
    ],
    name: "updateFeeData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "updateInterestIndexes",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IOracleManager",
        name: "newOracleManager",
        type: "address",
      },
    ],
    name: "updateOracleManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "bool", name: "isStable", type: "bool" },
    ],
    name: "updatePoolWithBorrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "updatePoolWithDeposit",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "fAmount", type: "uint256" },
          {
            internalType: "uint256",
            name: "depositInterestIndex",
            type: "uint256",
          },
          {
            components: [
              { internalType: "uint256", name: "price", type: "uint256" },
              { internalType: "uint8", name: "decimals", type: "uint8" },
            ],
            internalType: "struct DataTypes.PriceFeed",
            name: "priceFeed",
            type: "tuple",
          },
        ],
        internalType: "struct DataTypes.DepositPoolParams",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "updatePoolWithLiquidation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "amount", type: "uint256" },
      {
        internalType: "uint256",
        name: "oldLoanStableInterestRate",
        type: "uint256",
      },
    ],
    name: "updatePoolWithRebalanceDown",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "amount", type: "uint256" },
      {
        internalType: "uint256",
        name: "oldLoanStableInterestRate",
        type: "uint256",
      },
    ],
    name: "updatePoolWithRebalanceUp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "principalPaid", type: "uint256" },
      { internalType: "uint256", name: "interestPaid", type: "uint256" },
      { internalType: "uint256", name: "loanStableRate", type: "uint256" },
      { internalType: "uint256", name: "excessAmount", type: "uint256" },
    ],
    name: "updatePoolWithRepay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "principalPaid", type: "uint256" },
      { internalType: "uint256", name: "interestPaid", type: "uint256" },
      { internalType: "uint256", name: "loanStableRate", type: "uint256" },
    ],
    name: "updatePoolWithRepayWithCollateral",
    outputs: [
      {
        components: [{ internalType: "uint256", name: "fAmount", type: "uint256" }],
        internalType: "struct DataTypes.RepayWithCollateralPoolParams",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "loanBorrowAmount", type: "uint256" },
      { internalType: "bool", name: "switchingToStable", type: "bool" },
      {
        internalType: "uint256",
        name: "oldLoanBorrowStableRate",
        type: "uint256",
      },
    ],
    name: "updatePoolWithSwitchBorrowType",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "underlyingAmount", type: "uint256" }],
    name: "updatePoolWithWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "sr0", type: "uint32" },
      { internalType: "uint32", name: "sr1", type: "uint32" },
      { internalType: "uint32", name: "sr2", type: "uint32" },
      { internalType: "uint32", name: "sr3", type: "uint32" },
      {
        internalType: "uint16",
        name: "optimalStableToTotalDebtRatio",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "rebalanceUpUtilisationRatio",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "rebalanceUpDepositInterestRate",
        type: "uint16",
      },
      { internalType: "uint16", name: "rebalanceDownDelta", type: "uint16" },
    ],
    name: "updateStableBorrowData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "vr0", type: "uint32" },
      { internalType: "uint32", name: "vr1", type: "uint32" },
      { internalType: "uint32", name: "vr2", type: "uint32" },
    ],
    name: "updateVariableBorrowData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "chainId", type: "uint16" },
      { internalType: "bytes32", name: "source", type: "bytes32" },
    ],
    name: "verifyReceiveToken",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;
