export const LoanManagerAbi = [
  {
    inputs: [
      { internalType: "address", name: "admin", type: "address" },
      {
        internalType: "contract IOracleManager",
        name: "oracleManager",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AccessControlBadConfirmation", type: "error" },
  {
    inputs: [{ internalType: "uint48", name: "schedule", type: "uint48" }],
    name: "AccessControlEnforcedDefaultAdminDelay",
    type: "error",
  },
  { inputs: [], name: "AccessControlEnforcedDefaultAdminRules", type: "error" },
  {
    inputs: [{ internalType: "address", name: "defaultAdmin", type: "address" }],
    name: "AccessControlInvalidDefaultAdmin",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "bytes32", name: "neededRole", type: "bytes32" },
    ],
    name: "AccessControlUnauthorizedAccount",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint8", name: "poolId", type: "uint8" }],
    name: "BorrowCapReached",
    type: "error",
  },
  { inputs: [], name: "BorrowFactorTooLow", type: "error" },
  { inputs: [], name: "BorrowRewardIndexTooHigh", type: "error" },
  {
    inputs: [{ internalType: "uint8", name: "poolId", type: "uint8" }],
    name: "CollateralCapReached",
    type: "error",
  },
  { inputs: [], name: "CollateralFactorTooHigh", type: "error" },
  { inputs: [], name: "CollateralRewardIndexTooHigh", type: "error" },
  { inputs: [], name: "LiquidationBonusTooHigh", type: "error" },
  { inputs: [], name: "LiquidationFeeTooHigh", type: "error" },
  {
    inputs: [{ internalType: "bytes32", name: "loanId", type: "bytes32" }],
    name: "LoanNotEmpty",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
    ],
    name: "LoanPoolAlreadyAdded",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
    ],
    name: "LoanPoolAlreadyDeprecated",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
    ],
    name: "LoanPoolDeprecated",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
    ],
    name: "LoanPoolUnknown",
    type: "error",
  },
  { inputs: [], name: "LoanTargetHealthTooLow", type: "error" },
  {
    inputs: [{ internalType: "uint16", name: "loanTypeId", type: "uint16" }],
    name: "LoanTypeAlreadyCreated",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint16", name: "loanTypeId", type: "uint16" }],
    name: "LoanTypeAlreadyDeprecated",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint16", name: "loanTypeId", type: "uint16" }],
    name: "LoanTypeDeprecated",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint16", name: "loanTypeId", type: "uint16" }],
    name: "LoanTypeUnknown",
    type: "error",
  },
  { inputs: [], name: "MathOverflowedMulDiv", type: "error" },
  {
    inputs: [
      { internalType: "bytes32", name: "loanId", type: "bytes32" },
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
    ],
    name: "NotAccountOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint8", name: "poolId", type: "uint8" }],
    name: "PoolAlreadyAdded",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint8", name: "poolId", type: "uint8" }],
    name: "PoolUnknown",
    type: "error",
  },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  {
    inputs: [
      { internalType: "uint8", name: "bits", type: "uint8" },
      { internalType: "uint256", name: "value", type: "uint256" },
    ],
    name: "SafeCastOverflowedUintDowncast",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "loanId", type: "bytes32" }],
    name: "SameLoan",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "loanId", type: "bytes32" }],
    name: "UnknownUserLoan",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "loanId", type: "bytes32" }],
    name: "UserLoanAlreadyCreated",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "loanId", type: "bytes32" }],
    name: "UserLoanInactive",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "loanId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "accountId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "loanTypeId",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "loanName",
        type: "bytes32",
      },
    ],
    name: "CreateUserLoan",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "DefaultAdminDelayChangeCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint48",
        name: "newDelay",
        type: "uint48",
      },
      {
        indexed: false,
        internalType: "uint48",
        name: "effectSchedule",
        type: "uint48",
      },
    ],
    name: "DefaultAdminDelayChangeScheduled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "DefaultAdminTransferCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newAdmin",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint48",
        name: "acceptSchedule",
        type: "uint48",
      },
    ],
    name: "DefaultAdminTransferScheduled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "loanId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "accountId",
        type: "bytes32",
      },
    ],
    name: "DeleteUserLoan",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint8", name: "poolId", type: "uint8" },
      {
        indexed: false,
        internalType: "uint256",
        name: "collateralRewardIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "borrowRewardIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lastUpdateTimestamp",
        type: "uint256",
      },
    ],
    name: "RewardIndexesUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "bytes32",
        name: "previousAdminRole",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "newAdminRole",
        type: "bytes32",
      },
    ],
    name: "RoleAdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleRevoked",
    type: "event",
  },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "HUB_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LISTING_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ORACLE_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REBALANCER_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "acceptDefaultAdminTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "contract IHubPool", name: "pool", type: "address" }],
    name: "addPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
      { internalType: "uint16", name: "collateralFactor", type: "uint16" },
      { internalType: "uint64", name: "collateralCap", type: "uint64" },
      { internalType: "uint16", name: "borrowFactor", type: "uint16" },
      { internalType: "uint64", name: "borrowCap", type: "uint64" },
      { internalType: "uint16", name: "liquidationBonus", type: "uint16" },
      { internalType: "uint16", name: "liquidationFee", type: "uint16" },
      {
        internalType: "uint256",
        name: "rewardCollateralSpeed",
        type: "uint256",
      },
      { internalType: "uint256", name: "rewardBorrowSpeed", type: "uint256" },
      { internalType: "uint256", name: "rewardMinimumAmount", type: "uint256" },
    ],
    name: "addPoolToLoanType",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newAdmin", type: "address" }],
    name: "beginDefaultAdminTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "loanId", type: "bytes32" },
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "maxStableRate", type: "uint256" },
    ],
    name: "borrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "cancelDefaultAdminTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint48", name: "newDelay", type: "uint48" }],
    name: "changeDefaultAdminDelay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint32", name: "loanTargetHealth", type: "uint32" },
    ],
    name: "createLoanType",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes4", name: "nonce", type: "bytes4" },
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "bytes32", name: "loanName", type: "bytes32" },
    ],
    name: "createUserLoan",
    outputs: [{ internalType: "bytes32", name: "loanId", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultAdmin",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultAdminDelay",
    outputs: [{ internalType: "uint48", name: "", type: "uint48" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultAdminDelayIncreaseWait",
    outputs: [{ internalType: "uint48", name: "", type: "uint48" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "loanId", type: "bytes32" },
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
    ],
    name: "deleteUserLoan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "loanId", type: "bytes32" },
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "loanId", type: "bytes32" },
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
      { internalType: "address", name: "sender", type: "address" },
      { internalType: "uint256", name: "fAmount", type: "uint256" },
    ],
    name: "depositFToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint16", name: "loanTypeId", type: "uint16" }],
    name: "deprecateLoanType",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
    ],
    name: "deprecatePoolInLoanType",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
    ],
    name: "getLoanPool",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "collateralUsed", type: "uint256" },
          { internalType: "uint256", name: "borrowUsed", type: "uint256" },
          { internalType: "uint64", name: "collateralCap", type: "uint64" },
          { internalType: "uint64", name: "borrowCap", type: "uint64" },
          { internalType: "uint16", name: "collateralFactor", type: "uint16" },
          { internalType: "uint16", name: "borrowFactor", type: "uint16" },
          { internalType: "uint16", name: "liquidationBonus", type: "uint16" },
          { internalType: "uint16", name: "liquidationFee", type: "uint16" },
          { internalType: "bool", name: "isAdded", type: "bool" },
          { internalType: "bool", name: "isDeprecated", type: "bool" },
          {
            components: [
              {
                internalType: "uint64",
                name: "lastUpdateTimestamp",
                type: "uint64",
              },
              {
                internalType: "uint256",
                name: "minimumAmount",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "collateralSpeed",
                type: "uint256",
              },
              { internalType: "uint256", name: "borrowSpeed", type: "uint256" },
              {
                internalType: "uint256",
                name: "collateralRewardIndex",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "borrowRewardIndex",
                type: "uint256",
              },
            ],
            internalType: "struct LoanManagerState.LoanPoolReward",
            name: "reward",
            type: "tuple",
          },
        ],
        internalType: "struct LoanManagerState.LoanPool",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint16", name: "loanTypeId", type: "uint16" }],
    name: "getLoanTypeLoanTargetHealth",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOracleManager",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "poolId", type: "uint8" }],
    name: "getPool",
    outputs: [{ internalType: "contract IHubPool", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "loanId", type: "bytes32" }],
    name: "getType",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "loanId", type: "bytes32" }],
    name: "getUserLoan",
    outputs: [
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8[]", name: "colPools", type: "uint8[]" },
      { internalType: "uint8[]", name: "borPools", type: "uint8[]" },
      {
        components: [
          { internalType: "uint256", name: "balance", type: "uint256" },
          { internalType: "uint256", name: "rewardIndex", type: "uint256" },
        ],
        internalType: "struct LoanManagerState.UserLoanCollateral[]",
        name: "",
        type: "tuple[]",
      },
      {
        components: [
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "uint256", name: "balance", type: "uint256" },
          {
            internalType: "uint256",
            name: "lastInterestIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "stableInterestRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastStableUpdateTimestamp",
            type: "uint256",
          },
          { internalType: "uint256", name: "rewardIndex", type: "uint256" },
        ],
        internalType: "struct LoanManagerState.UserLoanBorrow[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
    ],
    name: "getUserPoolRewards",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "collateral", type: "uint256" },
          { internalType: "uint256", name: "borrow", type: "uint256" },
          { internalType: "uint256", name: "interestPaid", type: "uint256" },
        ],
        internalType: "struct LoanManagerState.UserPoolRewards",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint16", name: "loanTypeId", type: "uint16" }],
    name: "isLoanTypeCreated",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint16", name: "loanTypeId", type: "uint16" }],
    name: "isLoanTypeDeprecated",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "poolId", type: "uint8" }],
    name: "isPoolAdded",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
    ],
    name: "isPoolInLoanType",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
    ],
    name: "isPoolInLoanTypeDeprecated",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "loanId", type: "bytes32" }],
    name: "isUserLoanActive",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "loanId", type: "bytes32" },
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
    ],
    name: "isUserLoanOwner",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "violatorLoanId", type: "bytes32" },
      { internalType: "bytes32", name: "liquidatorLoanId", type: "bytes32" },
      { internalType: "bytes32", name: "liquidatorAccountId", type: "bytes32" },
      { internalType: "uint8", name: "colPoolId", type: "uint8" },
      { internalType: "uint8", name: "borPoolId", type: "uint8" },
      { internalType: "uint256", name: "maxRepayAmount", type: "uint256" },
      { internalType: "uint256", name: "minSeizedAmount", type: "uint256" },
    ],
    name: "liquidate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingDefaultAdmin",
    outputs: [
      { internalType: "address", name: "newAdmin", type: "address" },
      { internalType: "uint48", name: "schedule", type: "uint48" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingDefaultAdminDelay",
    outputs: [
      { internalType: "uint48", name: "newDelay", type: "uint48" },
      { internalType: "uint48", name: "schedule", type: "uint48" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "loanId", type: "bytes32" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
    ],
    name: "rebalanceDown",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "loanId", type: "bytes32" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
    ],
    name: "rebalanceUp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "loanId", type: "bytes32" },
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "maxOverRepayment", type: "uint256" },
    ],
    name: "repay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "loanId", type: "bytes32" },
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "repayWithCollateral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rollbackDefaultAdminDelay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "loanId", type: "bytes32" },
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
      { internalType: "uint256", name: "maxStableRate", type: "uint256" },
    ],
    name: "switchBorrowType",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
      { internalType: "uint16", name: "borrowFactor", type: "uint16" },
    ],
    name: "updateLoanPoolBorrowFactor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
      { internalType: "uint64", name: "collateralCap", type: "uint64" },
      { internalType: "uint64", name: "borrowCap", type: "uint64" },
    ],
    name: "updateLoanPoolCaps",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
      { internalType: "uint16", name: "collateralFactor", type: "uint16" },
    ],
    name: "updateLoanPoolCollateralFactor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
      { internalType: "uint16", name: "liquidationBonus", type: "uint16" },
      { internalType: "uint16", name: "liquidationFee", type: "uint16" },
    ],
    name: "updateLoanPoolLiquidation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16[]", name: "loanTypeIds", type: "uint16[]" },
      {
        internalType: "uint8[][]",
        name: "poolIdsForLoanType",
        type: "uint8[][]",
      },
    ],
    name: "updateLoanPoolsRewardIndexes",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint32", name: "loanTargetHealth", type: "uint32" },
    ],
    name: "updateLoanTypeLoanTargetHealth",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IOracleManager",
        name: "newOracleManager",
        type: "address",
      },
    ],
    name: "updateOracleManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "loanTypeId", type: "uint16" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
      { internalType: "uint256", name: "collateralSpeed", type: "uint256" },
      { internalType: "uint256", name: "borrowSpeed", type: "uint256" },
      { internalType: "uint256", name: "minimumAmount", type: "uint256" },
    ],
    name: "updateRewardParams",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32[]", name: "loanIds", type: "bytes32[]" }],
    name: "updateUserLoansPoolsRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "loanId", type: "bytes32" },
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "bool", name: "isFAmount", type: "bool" },
    ],
    name: "withdraw",
    outputs: [{ internalType: "uint256", name: "underlingAmount", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "loanId", type: "bytes32" },
      { internalType: "bytes32", name: "accountId", type: "bytes32" },
      { internalType: "uint8", name: "poolId", type: "uint8" },
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "uint256", name: "fAmount", type: "uint256" },
    ],
    name: "withdrawFToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
